<?xml version="1.0" encoding="utf-8"?><Database Name="TIER_PVBH" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SRVCOSTIER;Initial Catalog=TIER_PVBH;User ID=TIER" SettingsObjectName="RPGPP.Properties.Settings" SettingsPropertyName="TIER_PVBHConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FD__PROGRAM_CLIENT" Member="FD__PROGRAM_CLIENTs">
    <Type Name="FD__PROGRAM_CLIENT">
      <Column Name="OP__DOCID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OP__PARENTID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OP__FOLDERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdmissionKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdmitTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClientKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Date_Admit_Program" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Date_Discharged_Program" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Date_Form" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Date_Transferred" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DischTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FacilityKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LEGlStat" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="Number_of_Days" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PgmKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProgramAdmit_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Program_Code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Program_Status" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TransferFacilityKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransferProgramCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date_Transferred_Program" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProgramTransferedTo" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="BEDID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdmissionVisitType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceOfAdmission" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date_Proj_Discharge" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DischargeTypeDesc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeptKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EpisodeKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PsychStaffKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProgramAdmitDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DischargeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DischargeTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PgmAdmissionKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProgramAdmissionDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProgramDischargeDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BedKeyTransfer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="A06_A07_Transfer" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="A01_Admit" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PriorityAdmissionCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceAdmissionCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PatientStatusCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FD__PROGRAM_CLIENT_BLU_Program" Member="BLU_Programs" ThisKey="PgmKey" OtherKey="PgmNum" Type="BLU_Program" />
      <Association Name="FD__PROGRAM_CLIENT_FD__MEDS_PRESCRIPTION" Member="FD__MEDS_PRESCRIPTIONs" ThisKey="AdmissionKey" OtherKey="AdmissionKey" Type="FD__MEDS_PRESCRIPTION" />
      <Association Name="FD__CLIENT_FD__PROGRAM_CLIENT" Member="FD__CLIENT" ThisKey="ClientKey" OtherKey="OP__DOCID" Type="FD__CLIENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BLU_Programs" Member="BLU_Programs">
    <Type Name="BLU_Program">
      <Column Name="PgmKey" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PgmName" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="PgmNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeptKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocCode" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="BatchType" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="FacesheetName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Beds" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ServiceTypeKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Inactive" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Association Name="FD__PROGRAM_CLIENT_BLU_Program" Member="FD__PROGRAM_CLIENT" ThisKey="PgmNum" OtherKey="PgmKey" Type="FD__PROGRAM_CLIENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FD__MEDS_PRESCRIPTION" Member="FD__MEDS_PRESCRIPTIONs">
    <Type Name="FD__MEDS_PRESCRIPTION">
      <Column Name="OP__DOCID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OP__PARENTID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OP__FOLDERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdmissionKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AXISIII_medication_order" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="controlledsubstance" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DATE_FORM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DOSE1" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Frequency_Med" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="GenericOK" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="INSTRUCTIONS" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="medinfosheet_givento_pt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="MEDS_CODE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MEDS_DESC" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Ordered_by" Type="System.String" DbType="VarChar(41)" CanBeNull="true" />
      <Column Name="Refills" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TIME1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DischargePrescription" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="MEDICATIONKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STAFFKEY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClientKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NumOfPills" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DrugName1" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="PgmAdmissionKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PgmKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RcopiaID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SigAction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DoseForm" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Route" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="DoseOther" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Duration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityUnit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Voided" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Denied" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DateCompleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateSigned" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CompletionAction" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PharmacyName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Rationale" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DateFill" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateSigChanged" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateLastModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StopReason" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MedicationRcopiaID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="FD__PROGRAM_CLIENT_FD__MEDS_PRESCRIPTION" Member="FD__PROGRAM_CLIENT" ThisKey="AdmissionKey" OtherKey="AdmissionKey" Type="FD__PROGRAM_CLIENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FD__CLIENTS" Member="FD__CLIENTs">
    <Type Name="FD__CLIENT">
      <Column Name="OP__DOCID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OP__PARENTID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OP__FOLDERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="admissionkey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Alias" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ClientKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="VarChar(68)" CanBeNull="true" />
      <Column Name="NameF" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NameL" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NameMI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SSN" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="InquiryKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SELECTED_FOLDERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Language" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Responsiblepartykey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Client_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DateEntered" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NameSuffix" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Marital_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EthnicityCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EyeColor" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="HairColor" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="OTHER_MARKS" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PIERCINGS" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RaceCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TATTOO" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RcopiaID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MRN" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DrFirstUpload" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="FD__CLIENT_FD__PROGRAM_CLIENT" Member="FD__PROGRAM_CLIENTs" ThisKey="OP__DOCID" OtherKey="ClientKey" Type="FD__PROGRAM_CLIENT" />
    </Type>
  </Table>
  <Table Name="dbo.FD__IDENT_INFO" Member="FD__IDENT_INFOs">
    <Type Name="FD__IDENT_INFO">
      <Column Name="OP__DOCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OP__PARENTID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OP__FOLDERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdmissionKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Alias" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Caretaker" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Client_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClientKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateEntered" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ETHNICITYCODE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FacilityKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="VarChar(68)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="IdentifyingKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InquiryKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Language" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MARITALSTATUSCODE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NameF" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NameL" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NameMI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NameSuffix" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RACECODE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReligionCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Responsiblepartykey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SELECTED_FOLDERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSN" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="LangPriCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LangSecCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateOfDeath" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PrelimcauseofDeath" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="OrderConnSent" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SendtoOrderConn" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VWr__Medication_Prescription" Member="VWr__Medication_Prescriptions">
    <Type Name="VWr__Medication_Prescription">
      <Column Name="OP__DOCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DATE_FORM" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TIME1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Patient" Type="System.String" DbType="VarChar(68)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClAddress" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="AdmissionKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClientKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DrugName1" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="Generic" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="Strength" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="DOSE1" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Frequency_Med" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="INSTRUCTIONS" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Route" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Rationale" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Refills" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NumOfPills" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Staff" Type="System.String" DbType="VarChar(567)" CanBeNull="true" />
      <Column Name="NPI_ID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Dea" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="VarChar(567)" CanBeNull="true" />
      <Column Name="[Supervisor NPI]" Member="Supervisor_NPI" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="[Supervisor DEA]" Member="Supervisor_DEA" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FD__FACILITIES" Member="FD__FACILITIES">
    <Type Name="FD__FACILITIES">
      <Column Name="OP__DOCID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OP__PARENTID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OP__FOLDERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Above_Lvl_Exit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ADDRESS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Below_Lvl_Exit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Building_Type" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CITY" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Classification" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Direct_Alarm_Connection" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="FacilityKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Fire_Alarm" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="Licensed_Beds" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="No_Stores" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Occupancy_Type" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Occupied_By_Org" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PHONE" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Smoke_Detector" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="Sprinkler_System" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="Square_Footage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Unlicensed_Beds" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Where_Direct_Alarm" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="Where_Smoke_Detection" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Where_Sprinkler_System" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Year_Built" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZIP" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ADDRESS2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FacilityName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="BuildingUsed" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="BuildingTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OccupancyTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OccupiedByOrg" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="FamilyKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateEffective" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateExpire" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
    </Type>
  </Table>
</Database>